title = "Gnarly Void"
description = "Various wares from the PNW"
base_url = "https://gnarlyvoid.com"

compile_sass = false
build_search_index = false

[[taxonomies]]
name = "tags"
feed = true

generate_feeds = true
feed_filenames = ["rss.xml"]

[markdown.highlighting]
theme = "gruvbox-dark-hard"

[extra]
